NuGet = ..\.nuget\NuGet.exe
Name = FileVer.

SPEC:
	@ECHO CREATING SPEC...
	 $(NuGet) spec $(Name)csproj

PACK: SPEC CLEAN
	@ECHO CREATING PACK...
	$(NuGet) pack $(Name)csproj -Prop Configuration=Release

PUSH:
	@ECHO PUSHING PACK...
	$(NuGet) push $(Name)*.nupkg

CLEAN:
	@ECHO CLEANING PACKS...
	del $(Name)*.nupkg